import express, { Express, Router } from "express";
import { legacyAuthUsageMonitor } from "../helpers/auth/legacyAuthUsageMonitor";
import { requirePassword, uploadsDir } from "../helpers/auth/requirePassword";
import { requireSessionAuth } from "../helpers/auth/requireSessionAuth";
import arcgisRouter from "../routes/arcgis";
import authRouter from "../routes/auth";
import authKeycloak from "../routes/auth/authKeycloak";
import constsRouter from "../routes/consts";
import devicesUpdatesRouter from "../routes/devices-updates";
import directDownloadRouter from "../routes/directDownload";
import emailsRouter from "../routes/emails";
import fileDownloadRouter from "../routes/fileDownload";
import finishedPlansRouter from "../routes/finished_plans";
import flightPlansRouter from "../routes/flightPlans";
import geometriesRouter from "../routes/geometries";
import installersRouter from "../routes/installers";
import keycloakRouter from "../routes/keycloak";
import logsRouter from "../routes/logs";
import main from "../routes/main";
import pointsRouter from "../routes/points";
import reportUploadRouter from "../routes/reportUpload";
import templateFlightsRouter from "../routes/template_plans";
import timesliderRouter from "../routes/timeslider";
import usersRouter from "../routes/users";

export function registerApplicationRoutes(app: Express, auth2Router: Router) {
  app.use(legacyAuthUsageMonitor);
  app.use("/", main);
  app.use("/auth", authKeycloak);
  app.use("/auth2", auth2Router);
  app.use("/api/keycloak", requireSessionAuth, keycloakRouter);
  app.use("/api/auth", requireSessionAuth, authRouter);
  app.use("/api/users", requireSessionAuth, usersRouter);
  app.use("/api/flightPlans", requireSessionAuth, flightPlansRouter);
  app.use("/api/points", requireSessionAuth, pointsRouter);
  app.use("/api/emails", requireSessionAuth, emailsRouter);
  app.use("/api/finished_plans", requireSessionAuth, finishedPlansRouter);
  app.use("/api/templateFlight", requireSessionAuth, templateFlightsRouter);
  app.use("/api/logs", requireSessionAuth, logsRouter);
  app.use("/api/consts", requireSessionAuth, constsRouter);
  app.use("/api/geometries", requireSessionAuth, geometriesRouter);
  app.use("/api/timeslider", requireSessionAuth, timesliderRouter);
  app.use("/api/arcgis", requireSessionAuth, arcgisRouter);
  app.use("/uploads", requirePassword, express.static(uploadsDir));
  app.use("/api/upload-report", requireSessionAuth, reportUploadRouter);
  app.use("/api/file-download", fileDownloadRouter);
  app.use("/api/direct-download", directDownloadRouter);
  app.use("/api/installers", requireSessionAuth, installersRouter);
  app.use("/api/devices-updates", devicesUpdatesRouter);
}
