export const layersWithRegios: {
  id: string;
  title: string;
  url: string;
  regios: string[];
}[] = [
  {
    id: "8.4.1",
    title: "Hoogspanningsmasten",
    url: "",
    regios: [],
  },
  {
    id: "8.4.2",
    title: "Hoogspanningsleidingen",
    url: "",
    regios: [],
  },
  {
    id: "8.5",
    title: "Windenergiebieden",
    url: "",
    regios: [],
  },
  {
    id: "8.6",
    title: "Vakken_zandwinning",
    url: "",
    regios: ["MN"],
  },
  {
    id: "8.7",
    title: "vergunde_vlakken_zandwinning",
    url: "",
    regios: ["MN"],
  },
  {
    id: "8.8",
    title: "Drone Fly-No Zone",
    url: "",
    regios: ["NN", "WNZ", "WNN"],
  },
  {
    id: "8.9",
    title: "Natura2000",
    url: "",
    regios: ["WNN", "WNZ"],
  },
  {
    id: "8.3",
    title: "Vaarwegen",
    url: "",
    regios: ["NN", "MN"],
  },
  {
    id: "8.1.1",
    title: "Hectometerpaaltjes",
    url: "",
    regios: ["WNZ", "ZN"],
  },
  {
    id: "8.1.2",
    title: "Wegen",
    url: "",
    regios: ["WNZ", "ON", "ZN"],
  },
  {
    id: "9.1",
    title: "Betonning Totaal",
    url: "",
    regios: ["NN", "MN"],
  },
  {
    id: "9.2",
    title: "ARZ",
    url: "",
    regios: [],
  },
  {
    id: "9.3",
    title: "Strandpaviljoens",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.4",
    title: "Strandpalen",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.5",
    title: "Damnummers",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.6",
    title: "Lozingspunten",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.7",
    title: "Vloestofleidingen",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.8",
    title: "Data_Telecom",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.9",
    title: "Electrkabels",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.10",
    title: "Gasleidingen",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.11",
    title: "Primaire_keringen",
    url: "",
    regios: ["NN", "MN"],
  },
  {
    id: "9.12",
    title: "Vaarwegen",
    url: "",
    regios: ["NN", "MN"],
  },
  {
    id: "9.13",
    title: "Snelvaren",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.14",
    title: "Strandovergangen",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.15",
    title: "Wadlooproutes",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.16",
    title: "Tycomkabel",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.17",
    title: "NGTleiding",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.18",
    title: "NorNedkabel",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.19",
    title: "Kwelderdammen",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.20",
    title: "Eemsverdrag",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.21",
    title: "Pierenwinning",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.22",
    title: "MZI_installaties2018",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.23",
    title: "MZI_locaties2018",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.24",
    title: "Mosselpercelen",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.25",
    title: "Schelpenwinning",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.26",
    title: "Bruggen_Sluizen_HLD",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.27",
    title: "BeheergrensHLD",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.28",
    title: "Waterregeling",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.29",
    title: "Paviljoens",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.30",
    title: "Verspreidingsvakken",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.31",
    title: "Kitesurfgebieden",
    url: "",
    regios: ["NN", "MN"],
  },
  {
    id: "9.32",
    title: "Artikel20_2017",
    url: "",
    regios: ["NN"],
  },
  {
    id: "9.33",
    title: "Natura2000_NN",
    url: "",
    regios: ["NN"],
  },
];
