import {
  nnFeatureLayerSpec,
  nnMapImageLayerSpec,
  toLegendLayerDefinitions,
} from "./nnederlandLayerBuilders";
import { nnLineIcon, nnSquareIcon, nnederlandLayerIcons } from "./nnederlandLayerIcons";

const NN = ["NN"] as const;
const NN_MN = ["NN", "MN"] as const;

const layerSpecs = [
  nnFeatureLayerSpec({
    id: "9.1",
    serviceName: "Betonning_Totaal",
    title: "Betonning Totaal",
    icon: nnederlandLayerIcons.betonning,
    regio: [...NN_MN],
  }),
  nnFeatureLayerSpec({
    id: "9.2",
    serviceName: "ARZ",
    title: "ARZ",
    icon: nnederlandLayerIcons.arz,
  }),
  nnFeatureLayerSpec({
    id: "9.3",
    serviceName: "Strandpaviljoens",
    title: "Strandpaviljoens",
    icon: nnederlandLayerIcons.strandpaviljoens,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.4",
    serviceName: "Strandpalen",
    title: "Strandpalen",
    icon: nnederlandLayerIcons.strandpalen,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.5",
    serviceName: "Damnummers",
    title: "Damnummers",
    icon: nnederlandLayerIcons.damnummers,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.6",
    serviceName: "Lozingspunten",
    title: "Lozingspunten",
    icon: nnederlandLayerIcons.lozingspunten,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.7",
    serviceName: "Vloeistofleidingen",
    title: "Vloestofleidingen",
    icon: nnLineIcon("#1e40af"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.8",
    serviceName: "DataTelecom",
    title: "DataTelecom",
    icon: nnLineIcon("#4ade80"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.9",
    serviceName: "Electrkabels",
    title: "Electrkabels",
    icon: nnLineIcon("#ef4444"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.10",
    serviceName: "Gasleidingen",
    title: "Gasleidingen",
    icon: nnLineIcon("#f97316"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.11",
    serviceName: "Primaire_keringen",
    title: "Primaire_keringen",
    icon: nnLineIcon("#22c55e", 7),
    regio: [...NN_MN],
  }),
  nnMapImageLayerSpec({
    id: "9.12",
    url: "https://geo.rijkswaterstaat.nl/arcgis/rest/services/GDR/nwb_wegen/MapServer/2",
    title: "Vaarwegen",
    icon: nnLineIcon("#1d4ed8"),
    regio: [...NN_MN],
  }),
  nnFeatureLayerSpec({
    id: "9.13",
    serviceName: "Snelvaren",
    title: "Snelvaren",
    icon: nnLineIcon("#bfdbfe"),
    regio: [...NN_MN],
  }),
  nnFeatureLayerSpec({
    id: "9.14",
    serviceName: "Strandovergangen",
    title: "Strandovergangen",
    icon: nnLineIcon("#fef08a", 6),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.15",
    serviceName: "Wadlooproutes",
    title: "Wadlooproutes",
    icon: nnLineIcon("#bbf7d0", 8),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.16",
    serviceName: "Tycomkabel",
    title: "Tycomkabel",
    icon: nnLineIcon("#4ade80"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.17",
    serviceName: "NGTleiding",
    title: "NGTleiding",
    icon: nnLineIcon("#fb923c"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.18",
    serviceName: "NorNedkabel",
    title: "NorNedkabel",
    icon: nnLineIcon("#ef4444"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.19",
    serviceName: "Kwelderdammen",
    title: "Kwelderdammen",
    icon: nnederlandLayerIcons.kwelderdammen,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.20",
    serviceName: "Eemsverdrag",
    title: "Eemsverdrag",
    icon: nnederlandLayerIcons.eemsverdrag,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.21",
    serviceName: "Pierenwinning",
    title: "Pierenwinning",
    icon: nnSquareIcon("#000000", "#fbcfe8", 1.5),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.22",
    serviceName: "MZI_installaties2018",
    title: "MZI_installaties2018",
    icon: nnSquareIcon("#000000", "#fed7aa"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.23",
    serviceName: "MZI_locaties2018",
    title: "MZI_locaties",
    icon: nnSquareIcon("#000000", "#e9d5ff", 1.5),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.24",
    serviceName: "Mosselpercelen",
    title: "Mosselpercelen",
    icon: nnSquareIcon("#000000", "#bfdbfe"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.25",
    serviceName: "Schelpenwinning",
    title: "Schelpenwinning",
    icon: nnSquareIcon("#000000", "#fbcfe8", 1.5),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.26",
    serviceName: "Bruggen_Sluizen_HLD",
    title: "Bruggen_Sluizen_HLD",
    icon: nnederlandLayerIcons.bruggenSluizen,
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.27",
    serviceName: "BeheersgrensHLD",
    title: "BeheersgrensHLD",
    icon: nnSquareIcon("#000000", "#a855f7"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.28",
    serviceName: "Waterregeling",
    title: "Waterregeling",
    icon: nnSquareIcon("#000000", "#fef08a"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.29",
    serviceName: "Paviljoens",
    title: "Paviljoens",
    icon: nnSquareIcon("#000000", "#f97316"),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.30",
    serviceName: "Verspreidingsvakken",
    title: "Verspreidingsvakken",
    icon: nnSquareIcon("#000000", "rgba(187, 247, 208, 0.5)", 1.5),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.31",
    serviceName: "Kitesurfgebieden",
    title: "Kitesurfgebieden",
    icon: nnSquareIcon("#000000", "#e9d5ff", 1.5),
    regio: [...NN_MN],
  }),
  nnFeatureLayerSpec({
    id: "9.32",
    serviceName: "Artikel20_2017",
    title: "Artikel20_2017",
    icon: nnSquareIcon("#000000", "#4ade80", 1.5),
    regio: [...NN],
  }),
  nnFeatureLayerSpec({
    id: "9.33",
    serviceName: "Natura2000_NN",
    title: "Natura2000_NN",
    icon: nnSquareIcon("#000000", "#65a30d"),
    regio: [...NN],
  }),
];

export const NNEDERLAND_LAYERS = toLegendLayerDefinitions(layerSpecs);
